import {useEffect,useRef,useState} from "react";
import * as api from "./api.js";
import {loadAnalytics,readConsent,setConsent,track} from "./analytics.js";
import {emptyLikedMemoriesCopy} from "./copy.js";
import {WelcomeScreen} from "./WelcomeScreen.js";

function Login({role,onDone}:{role:"family"|"admin";onDone:()=>void}){const[p,setP]=useState("");const[e,setE]=useState(false);return <main className="cover"><div className="login"><div className="star">✦</div><h1>{role==="family"?"Our little moments":"Owner statistics"}</h1><p>{role==="family"?"A small collection of days we never want to forget.":"Private access"}</p><form onSubmit={async event=>{event.preventDefault();setE(false);try{await api.login(role,p);onDone()}catch{setE(true)}}}><input autoFocus type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Family password" aria-label="Password"/><button>Enter</button>{e&&<p className="error">That password didn’t work.</p>}</form></div></main>}

function ConsentPrompt({id}:{id?:string}){const[c,setC]=useState(readConsent());if(!id||c)return null;const choose=(v:"granted"|"denied")=>{setConsent(v,id);setC(v)};return <aside className="consent"><p>Allow anonymous visit analytics? Photo identities always stay private.</p><button onClick={()=>choose("granted")}>Allow analytics</button><button className="quiet" onClick={()=>choose("denied")}>No thanks</button></aside>}

function Slideshow(){const[list,setList]=useState<api.Playlist|null>(null);const[index,setIndex]=useState(0);const[paused,setPaused]=useState(false);const[muted,setMuted]=useState(false);const[controls,setControls]=useState(true);const audio=useRef<HTMLAudioElement>(null);const video=useRef<HTMLVideoElement>(null);const item=list?.items[index];
 useEffect(()=>{if(!item||paused)return;const count=setTimeout(()=>void api.countDisplay(item.impressionToken).catch(()=>{}),2000);const advance=item.type==="IMAGE"?setTimeout(()=>setIndex(i=>(i+1)%list!.items.length),list!.photoDurationMs):undefined;return()=>{clearTimeout(count);if(advance)clearTimeout(advance)}},[item,paused,list]);
 useEffect(()=>{if(!controls)return;const timer=setTimeout(()=>setControls(false),3000);return()=>clearTimeout(timer)},[controls,index]);
 useEffect(()=>{if(item?.type==="VIDEO")audio.current?.pause();else if(!paused)void audio.current?.play().catch(()=>{})},[item,paused]);
 useEffect(()=>{if(item?.type!=="VIDEO")return;if(paused)video.current?.pause();else void video.current?.play().catch(()=>{})},[item,paused]);
 if(!list)return <><WelcomeScreen onBegin={async()=>{const p=await api.createPlaylist();setList(p);track("slideshow_started");setTimeout(()=>void audio.current?.play().catch(()=>{}))}}/><audio ref={audio} src="/api/soundtrack" loop muted={muted}/></>;
 if(!item)return <main className="cover"><div className="login"><h1>{emptyLikedMemoriesCopy.title}</h1><p>{emptyLikedMemoriesCopy.detail}</p></div></main>;
 const move=(delta:number)=>setIndex(i=>(i+delta+list.items.length)%list.items.length);
 return <main className={`stage ${controls?"controls-visible":""}`} onPointerMove={()=>setControls(true)} onClick={()=>setControls(true)}>{item.type==="IMAGE"?<img key={item.id} className="media kenburns" src={item.mediaUrl}/>:<video ref={video} key={item.id} className="media" src={item.mediaUrl} autoPlay={!paused} muted={muted} onEnded={()=>move(1)} playsInline/>}<div className="shade"/>{item.ageLabel&&<p className="age">{item.ageLabel}</p>}<nav className="controls"><button onClick={()=>move(-1)} aria-label="Previous">‹</button><button onClick={()=>setPaused(v=>!v)}>{paused?"▶":"Ⅱ"}</button><button onClick={()=>move(1)} aria-label="Next">›</button><button onClick={()=>setMuted(v=>!v)} aria-label={muted?"Unmute":"Mute"}>{muted?"🔇":"🔊"}</button><button onClick={()=>void document.documentElement.requestFullscreen?.()} aria-label="Fullscreen">⛶</button></nav><audio ref={audio} src="/api/soundtrack" loop muted={muted}/></main>}

function Family(){const[ready,setReady]=useState<boolean|null>(null);const[ga,setGa]=useState<string>();useEffect(()=>{void api.status("family").then(v=>setReady(v.authenticated));void fetch("/api/public-config").then(r=>r.json()).then(v=>{setGa(v.ga4MeasurementId);if(readConsent()==="granted")loadAnalytics(v.ga4MeasurementId);track("page_view")})},[]);if(ready===null)return null;return <>{ready?<Slideshow/>:<Login role="family" onDone={()=>setReady(true)}/>}<ConsentPrompt id={ga}/></>}

function Admin(){const[ok,setOk]=useState<boolean|null>(null);const[period,setPeriod]=useState("all");const[type,setType]=useState("all");const[items,setItems]=useState<Awaited<ReturnType<typeof api.getStats>>["items"]>([]);const load=()=>api.getStats(period,type).then(v=>setItems(v.items));useEffect(()=>{void api.status("admin").then(v=>setOk(v.authenticated))},[]);useEffect(()=>{if(ok)void load()},[ok,period,type]);if(ok===null)return null;if(!ok)return <Login role="admin" onDone={()=>setOk(true)}/>;return <main className="admin"><header><h1>Most displayed</h1><button onClick={()=>void api.logout("admin").then(()=>setOk(false))}>Log out</button></header><div className="filters"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7d">7 days</option><option value="30d">30 days</option><option value="all">All time</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All media</option><option value="IMAGE">Photos</option><option value="VIDEO">Videos</option></select><a href={`/api/admin/stats.csv?period=${period}&type=${type}`}>Export CSV</a></div><section className="grid">{items.map((item,i)=><article key={item.assetId}><span className="rank">#{i+1}</span><img src={item.thumbnailUrl}/><div><strong>{item.periodCount} displays</strong><small>{item.mediaType.toLowerCase()} · {item.totalCount} total</small></div></article>)}</section><button className="danger" onClick={async()=>{if(prompt('Type RESET to clear statistics')==='RESET'){await api.resetStats();await load()}}}>Reset statistics</button></main>}
export function App(){return location.pathname.startsWith("/admin")?<Admin/>:<Family/>}
